/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ClaimApi,
  ContractApi,
  EventApi,
  FulfillmentApi,
  InvoiceApi,
  MerchantApi,
  OrderApi,
  ProductApi,
  QuoteApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { SeelCustom } from "./client-custom";

export class Seel extends SeelCustom {
  readonly claim: ClaimApi;
  readonly contract: ContractApi;
  readonly event: EventApi;
  readonly fulfillment: FulfillmentApi;
  readonly invoice: InvoiceApi;
  readonly merchant: MerchantApi;
  readonly order: OrderApi;
  readonly product: ProductApi;
  readonly quote: QuoteApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.claim = new ClaimApi(configuration);
    this.contract = new ContractApi(configuration);
    this.event = new EventApi(configuration);
    this.fulfillment = new FulfillmentApi(configuration);
    this.invoice = new InvoiceApi(configuration);
    this.merchant = new MerchantApi(configuration);
    this.order = new OrderApi(configuration);
    this.product = new ProductApi(configuration);
    this.quote = new QuoteApi(configuration);
  }

}
