/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * The first line of the shipping address
     * @type {string}
     * @memberof Address
     */
    'address_1': string;
    /**
     * The second line of the shipping address
     * @type {string}
     * @memberof Address
     */
    'address_2'?: string;
    /**
     * The city of the shipping address
     * @type {string}
     * @memberof Address
     */
    'city': string;
    /**
     * The state or province code of the shipping address
     * @type {string}
     * @memberof Address
     */
    'state': string;
    /**
     * The zipcode of the shipping address
     * @type {string}
     * @memberof Address
     */
    'zipcode': string;
    /**
     * ISO 3166-1 alpha-2 country code of the shipping address
     * @type {string}
     * @memberof Address
     */
    'country': string;
}

