/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ClaimClaimDetailsInnerClaimItemsInner
 */
export interface ClaimClaimDetailsInnerClaimItemsInner {
    /**
     * The line item id covered by the contract.
     * @type {string}
     * @memberof ClaimClaimDetailsInnerClaimItemsInner
     */
    'line_item_id'?: string;
    /**
     * The quantity of the line item covered by the contract.
     * @type {number}
     * @memberof ClaimClaimDetailsInnerClaimItemsInner
     */
    'quantity'?: number;
    /**
     * The reason of the claim.
     * @type {string}
     * @memberof ClaimClaimDetailsInnerClaimItemsInner
     */
    'reason'?: string;
}

