/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Claim } from './claim';

/**
 * 
 * @export
 * @interface ClaimGetAllClaimsResponse
 */
export interface ClaimGetAllClaimsResponse {
    /**
     * Current page number.
     * @type {number}
     * @memberof ClaimGetAllClaimsResponse
     */
    'page'?: number;
    /**
     * Number of claims per page.
     * @type {number}
     * @memberof ClaimGetAllClaimsResponse
     */
    'page_size'?: number;
    /**
     * Total number of claims.
     * @type {number}
     * @memberof ClaimGetAllClaimsResponse
     */
    'total'?: number;
    /**
     * List of claims.
     * @type {Array<Claim>}
     * @memberof ClaimGetAllClaimsResponse
     */
    'claims'?: Array<Claim>;
}

