/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClaimClaimDetailsInner } from './claim-claim-details-inner';

/**
 * 
 * @export
 * @interface Claim
 */
export interface Claim {
    /**
     * The unique identifier of the claim.
     * @type {string}
     * @memberof Claim
     */
    'claim_id'?: string;
    /**
     * The identifier of the order associated with the claim.
     * @type {string}
     * @memberof Claim
     */
    'order_id'?: string;
    /**
     * The identifier of the contract associated with the claim.
     * @type {string}
     * @memberof Claim
     */
    'contract_id'?: string;
    /**
     * The settled amount of the claim.
     * @type {number}
     * @memberof Claim
     */
    'payout_amount'?: number;
    /**
     * The status of the claim.
     * @type {string}
     * @memberof Claim
     */
    'status'?: ClaimStatusEnum;
    /**
     * The status of the claim.
     * @type {string}
     * @memberof Claim
     */
    'claim_type'?: ClaimClaimTypeEnum;
    /**
     * The reject reason of the claim.
     * @type {string}
     * @memberof Claim
     */
    'reject_reason'?: string;
    /**
     * Items related to the claim
     * @type {Array<ClaimClaimDetailsInner>}
     * @memberof Claim
     */
    'claim_details'?: Array<ClaimClaimDetailsInner>;
    /**
     * The timestamp in milliseconds when the contract was cancelled (if applicable).
     * @type {string}
     * @memberof Claim
     */
    'updated_ts'?: string | null;
    /**
     * The timestamp in milliseconds when the contract was created.
     * @type {string}
     * @memberof Claim
     */
    'created_ts'?: string | null;
}

type ClaimStatusEnum = 'pending' | 'accepted' | 'rejected'
type ClaimClaimTypeEnum = 'return' | 'loss' | 'damage' | 'delay' | 'theft'


