/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Contract } from './contract';

/**
 * 
 * @export
 * @interface ContractListContractsResponse
 */
export interface ContractListContractsResponse {
    /**
     * Current page number.
     * @type {number}
     * @memberof ContractListContractsResponse
     */
    'page'?: number;
    /**
     * Number of contracts per page.
     * @type {number}
     * @memberof ContractListContractsResponse
     */
    'page_size'?: number;
    /**
     * Total number of contracts.
     * @type {number}
     * @memberof ContractListContractsResponse
     */
    'total'?: number;
    /**
     * List of contracts.
     * @type {Array<Contract>}
     * @memberof ContractListContractsResponse
     */
    'contracts'?: Array<Contract>;
}

