/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * The unique identifier for the customer
     * @type {string}
     * @memberof Customer
     */
    'customer_id': string;
    /**
     * The first name of the customer
     * @type {string}
     * @memberof Customer
     */
    'first_name'?: string;
    /**
     * The last name of the customer
     * @type {string}
     * @memberof Customer
     */
    'last_name'?: string;
    /**
     * The email address of the customer
     * @type {string}
     * @memberof Customer
     */
    'email': string;
    /**
     * The phone number of the customer
     * @type {string}
     * @memberof Customer
     */
    'phone'?: string;
    /**
     * Extra information about the product.
     * @type {object}
     * @memberof Customer
     */
    'extra_info'?: object;
}

