/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * Event ID
     * @type {string}
     * @memberof Event
     */
    'event_id'?: string;
    /**
     * Session ID
     * @type {string}
     * @memberof Event
     */
    'session_id'?: string;
    /**
     * Event created timestamp
     * @type {string}
     * @memberof Event
     */
    'event_ts'?: string;
    /**
     * Customer ID
     * @type {string}
     * @memberof Event
     */
    'customer_id'?: string;
    /**
     * Device ID
     * @type {string}
     * @memberof Event
     */
    'device_id'?: string;
    /**
     * Browser IP address
     * @type {string}
     * @memberof Event
     */
    'browser_ip'?: string;
    /**
     * Event source
     * @type {string}
     * @memberof Event
     */
    'event_source'?: string;
    /**
     * Event type
     * @type {string}
     * @memberof Event
     */
    'event_type'?: EventEventTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof Event
     */
    'event_info'?: object;
}

type EventEventTypeEnum = 'product_page_enter' | 'product_page_exit' | 'product_share' | 'favorite_add' | 'favorite_remove' | 'cart_add' | 'cart_remove' | 'ra_checked' | 'ra_unchecked' | 'checkout_begin' | 'checkout_complete'


