/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FulfillmentLineItemsInner
 */
export interface FulfillmentLineItemsInner {
    /**
     * The id of the line item.
     * @type {string}
     * @memberof FulfillmentLineItemsInner
     */
    'line_item_id': string;
    /**
     * The quantity of the line item.
     * @type {number}
     * @memberof FulfillmentLineItemsInner
     */
    'quantity': number;
}

