/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FulfillmentLineItemsInner } from './fulfillment-line-items-inner';

/**
 * 
 * @export
 * @interface Fulfillment
 */
export interface Fulfillment {
    /**
     * Fulfillment ID
     * @type {string}
     * @memberof Fulfillment
     */
    'fulfillment_id': string;
    /**
     * Fulfillment created timestamp in milliseconds
     * @type {string}
     * @memberof Fulfillment
     */
    'created_ts': string;
    /**
     * Fulfillment updated timestamp in milliseconds
     * @type {string}
     * @memberof Fulfillment
     */
    'updated_ts': string;
    /**
     * The tracking number of the fulfillment
     * @type {string}
     * @memberof Fulfillment
     */
    'tracking_number': string;
    /**
     * The shipping carrier of the fulfillment
     * @type {string}
     * @memberof Fulfillment
     */
    'carrier': string;
    /**
     * The tracking url of the fulfillment
     * @type {string}
     * @memberof Fulfillment
     */
    'tracking_url'?: string;
    /**
     * The shipping status of the fulfillment
     * @type {string}
     * @memberof Fulfillment
     */
    'shipment_status': FulfillmentShipmentStatusEnum;
    /**
     * The list of items included in the fulfillment.
     * @type {Array<FulfillmentLineItemsInner>}
     * @memberof Fulfillment
     */
    'line_items': Array<FulfillmentLineItemsInner>;
}

type FulfillmentShipmentStatusEnum = 'shipped' | 'delivered'


