/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FulfillmentUpdateFulfillmentDetailsRequestLineItemsInner } from './fulfillment-update-fulfillment-details-request-line-items-inner';

/**
 * 
 * @export
 * @interface FulfillmentUpdateFulfillmentDetailsRequest
 */
export interface FulfillmentUpdateFulfillmentDetailsRequest {
    /**
     * Fulfillment updated timestamp in milliseconds
     * @type {string}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'updated_ts': string;
    /**
     * The tracking number of the fulfillment
     * @type {string}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'tracking_number': string;
    /**
     * The shipping carrier of the fulfillment
     * @type {string}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'carrier': string;
    /**
     * The tracking url of the fulfillment
     * @type {string}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'tracking_url'?: string;
    /**
     * The shipping status of the fulfillment
     * @type {string}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'shipment_status': FulfillmentUpdateFulfillmentDetailsRequestShipmentStatusEnum;
    /**
     * The list of items included in the fulfillment.
     * @type {Array<FulfillmentUpdateFulfillmentDetailsRequestLineItemsInner>}
     * @memberof FulfillmentUpdateFulfillmentDetailsRequest
     */
    'line_items': Array<FulfillmentUpdateFulfillmentDetailsRequestLineItemsInner>;
}

type FulfillmentUpdateFulfillmentDetailsRequestShipmentStatusEnum = 'shipped' | 'delivered'


