/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoiceInvoiceItemsInner } from './invoice-invoice-items-inner';

/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * The ID of the invoice.
     * @type {string}
     * @memberof Invoice
     */
    'invoice_id'?: string;
    /**
     * The ID of the merchant.
     * @type {string}
     * @memberof Invoice
     */
    'merchant_id'?: string;
    /**
     * The number of the billing cycle.
     * @type {number}
     * @memberof Invoice
     */
    'billing_cycle'?: number;
    /**
     * The date when the merchant was charged for contracts sold.
     * @type {string}
     * @memberof Invoice
     */
    'billing_date'?: string;
    /**
     * The start date of the billing cycle.
     * @type {string}
     * @memberof Invoice
     */
    'billing_start_date'?: string;
    /**
     * The end date of the billing cycle.
     * @type {string}
     * @memberof Invoice
     */
    'billing_end_date'?: string;
    /**
     * The three-letter currency code (ISO 4217 format).
     * @type {string}
     * @memberof Invoice
     */
    'currency'?: string;
    /**
     * The status of the invoice.
     * @type {string}
     * @memberof Invoice
     */
    'status'?: InvoiceStatusEnum;
    /**
     * The amount of the invoice.
     * @type {number}
     * @memberof Invoice
     */
    'invoice_amount'?: number;
    /**
     * URL of the invoice
     * @type {string}
     * @memberof Invoice
     */
    'invoice_link'?: string;
    /**
     * A list of contracts associated with this invoice.
     * @type {Array<InvoiceInvoiceItemsInner>}
     * @memberof Invoice
     */
    'invoice_items'?: Array<InvoiceInvoiceItemsInner>;
}

type InvoiceStatusEnum = 'unpaid' | 'paid'


