/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InvoiceInvoiceItemsInner
 */
export interface InvoiceInvoiceItemsInner {
    /**
     * The ID of the contract sold during the billing cycle.
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'contract_id'?: string;
    /**
     * The ID of the order.
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'order_id'?: string;
    /**
     * Order number
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'order_number'?: string;
    /**
     * The protection plan name.
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'product_type'?: string;
    /**
     * The timestamp when the contract was purchased.
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'created_ts'?: string;
    /**
     * The timestamp when the contract was cancelled.
     * @type {string}
     * @memberof InvoiceInvoiceItemsInner
     */
    'cancelled_ts'?: string;
    /**
     * The protection cost of the contract to collect from the merchant.
     * @type {number}
     * @memberof InvoiceInvoiceItemsInner
     */
    'amount_collected'?: number;
    /**
     * The amount refunded due to contract cancellation.
     * @type {number}
     * @memberof InvoiceInvoiceItemsInner
     */
    'amount_reconciled'?: number;
}

