/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Invoice } from './invoice';

/**
 * 
 * @export
 * @interface InvoiceListInvoicesResponse
 */
export interface InvoiceListInvoicesResponse {
    /**
     * Current page number.
     * @type {number}
     * @memberof InvoiceListInvoicesResponse
     */
    'page'?: number;
    /**
     * Number of invoices per page.
     * @type {number}
     * @memberof InvoiceListInvoicesResponse
     */
    'page_size'?: number;
    /**
     * Total number of invoices.
     * @type {number}
     * @memberof InvoiceListInvoicesResponse
     */
    'total'?: number;
    /**
     * List of invoices.
     * @type {Array<Invoice>}
     * @memberof InvoiceListInvoicesResponse
     */
    'invoices'?: Array<Invoice>;
}

