/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ItemShippingOrigin } from './item-shipping-origin';
import { ProductAttributes } from './product-attributes';

/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * The ID of the item.
     * @type {string}
     * @memberof Item
     */
    'line_item_id': string;
    /**
     * The ID of the product.
     * @type {string}
     * @memberof Item
     */
    'product_id': string;
    /**
     * The title of the product.
     * @type {string}
     * @memberof Item
     */
    'product_title': string;
    /**
     * The description of the product.
     * @type {string}
     * @memberof Item
     */
    'product_description'?: string;
    /**
     * The ID of the product variant.
     * @type {string}
     * @memberof Item
     */
    'variant_id'?: string;
    /**
     * The title of the product variant.
     * @type {string}
     * @memberof Item
     */
    'variant_title'?: string;
    /**
     * The sku of the product variant.
     * @type {string}
     * @memberof Item
     */
    'sku'?: string;
    /**
     * The ID of the seller.
     * @type {string}
     * @memberof Item
     */
    'seller_id'?: string;
    /**
     * The name of the seller.
     * @type {string}
     * @memberof Item
     */
    'seller_name'?: string;
    /**
     * The brand name of the product.
     * @type {string}
     * @memberof Item
     */
    'brand_name'?: string;
    /**
     * The quantity of the product.
     * @type {number}
     * @memberof Item
     */
    'quantity': number;
    /**
     * The price of the product.
     * @type {number}
     * @memberof Item
     */
    'price': number;
    /**
     * The allocated discounts of the product.
     * @type {number}
     * @memberof Item
     */
    'allocated_discounts': number;
    /**
     * The sales tax of the product.
     * @type {number}
     * @memberof Item
     */
    'sales_tax': number;
    /**
     * The retail price of the product.
     * @type {number}
     * @memberof Item
     */
    'retail_price'?: number;
    /**
     * The final price of the product.
     * @type {number}
     * @memberof Item
     */
    'final_price': number;
    /**
     * The currency of the price.
     * @type {string}
     * @memberof Item
     */
    'currency': string;
    /**
     * Whether the item requires shipping or not.
     * @type {boolean}
     * @memberof Item
     */
    'requires_shipping': boolean;
    /**
     * The URL of the product.
     * @type {string}
     * @memberof Item
     */
    'product_url'?: string;
    /**
     * The URL of the product image.
     * @type {string}
     * @memberof Item
     */
    'image_url'?: string;
    /**
     * The main category of the product.
     * @type {string}
     * @memberof Item
     */
    'category_1': string;
    /**
     * The sub category of the product.
     * @type {string}
     * @memberof Item
     */
    'category_2': string;
    /**
     * The sub category of the product.
     * @type {string}
     * @memberof Item
     */
    'category_3'?: string;
    /**
     * The sub category of the product.
     * @type {string}
     * @memberof Item
     */
    'category_4'?: string;
    /**
     * Whether the item is final sale or not.
     * @type {boolean}
     * @memberof Item
     */
    'is_final_sale': boolean;
    /**
     * The physical condition of the item (e.g. new, used, refurbished)
     * @type {string}
     * @memberof Item
     */
    'condition': ItemConditionEnum;
    /**
     * 
     * @type {ProductAttributes}
     * @memberof Item
     */
    'product_attributes'?: ProductAttributes;
    /**
     * 
     * @type {ItemShippingOrigin}
     * @memberof Item
     */
    'shipping_origin'?: ItemShippingOrigin;
    /**
     * Extra information about the product.
     * @type {object}
     * @memberof Item
     */
    'extra_info'?: object;
}

type ItemConditionEnum = 'new' | 'used' | 'refurbished'


