/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantSeelServicesInner
 */
export interface MerchantSeelServicesInner {
    /**
     * The product type for the service, e.g. seel-ra, seel-gsp.
     * @type {string}
     * @memberof MerchantSeelServicesInner
     */
    'type'?: string;
    /**
     * Boolean indicating if the service is currently enabled (\'true\') or disabled (\'false\') for the merchant.
     * @type {boolean}
     * @memberof MerchantSeelServicesInner
     */
    'is_enabled'?: boolean;
    /**
     * Default opt-in setting for the service widget. \'true\' means opted in by default. \'false\' means opted out by default.
     * @type {string}
     * @memberof MerchantSeelServicesInner
     */
    'is_default_on'?: string;
    /**
     * The reason why the service is disabled for this merchant if applicable.
     * @type {string}
     * @memberof MerchantSeelServicesInner
     */
    'disabled_reason'?: string;
    /**
     * The timestamp when the enabled service status was updated.
     * @type {string}
     * @memberof MerchantSeelServicesInner
     */
    'updated_ts'?: string;
}

