/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantSeelServicesInner } from './merchant-seel-services-inner';

/**
 * 
 * @export
 * @interface Merchant
 */
export interface Merchant {
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof Merchant
     */
    'merchant_id'?: string;
    /**
     * The identifier for the shop or store within the partner\'s platform.
     * @type {string}
     * @memberof Merchant
     */
    'shop_id'?: string;
    /**
     * The original subdomain domain for the shop provided by the ecommerce platform, e.g. subdomain.myshopify.com
     * @type {string}
     * @memberof Merchant
     */
    'admin_domain'?: string;
    /**
     * The custom domain name assigned to the shop, e.g. www.myshop.com.
     * @type {string}
     * @memberof Merchant
     */
    'shop_domain'?: string;
    /**
     * The source ecommerce platform for the shop, e.g. Shopify, BigCommerce.
     * @type {string}
     * @memberof Merchant
     */
    'shop_platform'?: string;
    /**
     * 3-letter ISO 4217 currency code for the primary currency used in the shop, e.g. USD, EUR.
     * @type {string}
     * @memberof Merchant
     */
    'shop_currency'?: string;
    /**
     * The registered business name for the shop.
     * @type {string}
     * @memberof Merchant
     */
    'shop_name'?: string;
    /**
     * The registered business name for the merchant.
     * @type {string}
     * @memberof Merchant
     */
    'contact_name'?: string;
    /**
     * The contact email address on file for the merchant.
     * @type {string}
     * @memberof Merchant
     */
    'contact_email'?: string;
    /**
     * The phone number on file for the merchant.
     * @type {string}
     * @memberof Merchant
     */
    'contact_phone_number'?: string;
    /**
     * 
     * @type {Array<MerchantSeelServicesInner>}
     * @memberof Merchant
     */
    'seel_services'?: Array<MerchantSeelServicesInner>;
    /**
     * The timestamp when the merchant was created.
     * @type {string}
     * @memberof Merchant
     */
    'created_ts'?: string;
    /**
     * The timestamp when the merchant was last updated.
     * @type {string}
     * @memberof Merchant
     */
    'updated_ts'?: string;
}

