/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantCreateNewMerchantRequestSeelServicesInner
 */
export interface MerchantCreateNewMerchantRequestSeelServicesInner {
    /**
     * The product type for the service, e.g. seel-ra, seel-gsp.
     * @type {string}
     * @memberof MerchantCreateNewMerchantRequestSeelServicesInner
     */
    'type': string;
    /**
     * Boolean indicating if the service is currently enabled (\'true\') or disabled (\'false\') for the merchant.
     * @type {boolean}
     * @memberof MerchantCreateNewMerchantRequestSeelServicesInner
     */
    'is_enabled'?: boolean;
    /**
     * Default opt-in setting for the service widget. \'true\' means opted in by default. \'false\' means opted out by default.
     * @type {boolean}
     * @memberof MerchantCreateNewMerchantRequestSeelServicesInner
     */
    'is_default_on': boolean;
}

