/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Merchant } from './merchant';

/**
 * 
 * @export
 * @interface MerchantListAllMerchantsResponse
 */
export interface MerchantListAllMerchantsResponse {
    /**
     * Current page number.
     * @type {number}
     * @memberof MerchantListAllMerchantsResponse
     */
    'page'?: number;
    /**
     * Number of merchants per page.
     * @type {number}
     * @memberof MerchantListAllMerchantsResponse
     */
    'page_size'?: number;
    /**
     * Total number of merchants.
     * @type {number}
     * @memberof MerchantListAllMerchantsResponse
     */
    'total'?: number;
    /**
     * List of merchants.
     * @type {Array<Merchant>}
     * @memberof MerchantListAllMerchantsResponse
     */
    'merchants'?: Array<Merchant>;
}

