/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';
import { Fulfillment } from './fulfillment';
import { Item } from './item';
import { OrderRefund } from './order-refund';
import { SeelService } from './seel-service';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * The unique identifier for the order in the system.
     * @type {string}
     * @memberof Order
     */
    'order_id'?: string;
    /**
     * The reference number that is visible to the merchant and shopper. Use the order ID value if there is no separate order number.
     * @type {string}
     * @memberof Order
     */
    'order_number'?: string;
    /**
     * The ID of a cart.
     * @type {string}
     * @memberof Order
     */
    'cart_id'?: string;
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof Order
     */
    'merchant_id'?: string;
    /**
     * The ID of the session.
     * @type {string}
     * @memberof Order
     */
    'session_id'?: string;
    /**
     * The ID of the client device.
     * @type {string}
     * @memberof Order
     */
    'device_id'?: string;
    /**
     * The IP address of the client.
     * @type {string}
     * @memberof Order
     */
    'client_ip'?: string;
    /**
     * Order created timestamp in milliseconds
     * @type {string}
     * @memberof Order
     */
    'created_ts'?: string;
    /**
     * Order cancelled timestamp in milliseconds
     * @type {string}
     * @memberof Order
     */
    'cancelled_ts'?: string;
    /**
     * Order updated timestamp in milliseconds
     * @type {string}
     * @memberof Order
     */
    'updated_ts'?: string;
    /**
     * The list of items included in the quote.
     * @type {Array<Item>}
     * @memberof Order
     */
    'line_items'?: Array<Item>;
    /**
     * 
     * @type {Address}
     * @memberof Order
     */
    'shipping_address'?: Address;
    /**
     * The list of fulfillments for the order.
     * @type {Array<Fulfillment>}
     * @memberof Order
     */
    'fulfillments'?: Array<Fulfillment>;
    /**
     * The list of Seel services of the order.
     * @type {Array<SeelService>}
     * @memberof Order
     */
    'seel_services'?: Array<SeelService>;
    /**
     * The list of refunds for the order.
     * @type {Array<OrderRefund>}
     * @memberof Order
     */
    'refunds'?: Array<OrderRefund>;
    /**
     * 
     * @type {Customer}
     * @memberof Order
     */
    'customer'?: Customer;
    /**
     * Additional information for the order
     * @type {object}
     * @memberof Order
     */
    'extra_info'?: object;
}

