/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Order } from './order';

/**
 * 
 * @export
 * @interface OrderBatchCreateOrdersResponse
 */
export interface OrderBatchCreateOrdersResponse {
    /**
     * The list of orders.
     * @type {Array<Order>}
     * @memberof OrderBatchCreateOrdersResponse
     */
    'orders'?: Array<Order>;
}

