/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Order } from './order';

/**
 * List of orders.
 * @export
 * @interface OrderBatchCreateOrdersRequest
 */
export interface OrderBatchCreateOrdersRequest {
    /**
     * The list of orders.
     * @type {Array<Order>}
     * @memberof OrderBatchCreateOrdersRequest
     */
    'orders'?: Array<Order>;
}

