/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrderRefundLineItemsInner } from './order-refund-line-items-inner';

/**
 * 
 * @export
 * @interface OrderRefund
 */
export interface OrderRefund {
    /**
     * The unique identifier of the claim.
     * @type {string}
     * @memberof OrderRefund
     */
    'refund_id'?: string;
    /**
     * The timestamp in milliseconds when the contract was created.
     * @type {string}
     * @memberof OrderRefund
     */
    'created_ts'?: string | null;
    /**
     * The refund amount.
     * @type {number}
     * @memberof OrderRefund
     */
    'refund_amount'?: number;
    /**
     * The refund reason.
     * @type {string}
     * @memberof OrderRefund
     */
    'refund_reason'?: string;
    /**
     * Items related to the refund
     * @type {Array<OrderRefundLineItemsInner>}
     * @memberof OrderRefund
     */
    'line_items'?: Array<OrderRefundLineItemsInner>;
}

