/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';
import { Item } from './item';
import { OrderCreateNewOrderRequestSeelServicesInner } from './order-create-new-order-request-seel-services-inner';

/**
 * 
 * @export
 * @interface OrderCreateNewOrderRequest
 */
export interface OrderCreateNewOrderRequest {
    /**
     * The unique identifier for the order in the system.
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'order_id': string;
    /**
     * The reference number that is visible to the merchant and shopper. Use the order ID value if there is no separate order number.
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'order_number': string;
    /**
     * Shopping session ID of the order
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'session_id': string;
    /**
     * Cart ID of the order
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'cart_id'?: string;
    /**
     * Merchant ID of the order
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'merchant_id'?: string;
    /**
     * The ID of the client device.
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'device_id'?: string;
    /**
     * The IP address of the client.
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'client_ip'?: string;
    /**
     * Order created timestamp in milliseconds
     * @type {string}
     * @memberof OrderCreateNewOrderRequest
     */
    'created_ts': string;
    /**
     * The list of items included in the order.
     * @type {Array<Item>}
     * @memberof OrderCreateNewOrderRequest
     */
    'line_items': Array<Item>;
    /**
     * 
     * @type {Address}
     * @memberof OrderCreateNewOrderRequest
     */
    'shipping_address': Address;
    /**
     * 
     * @type {Customer}
     * @memberof OrderCreateNewOrderRequest
     */
    'customer': Customer;
    /**
     * The list of Seel services of the order.
     * @type {Array<OrderCreateNewOrderRequestSeelServicesInner>}
     * @memberof OrderCreateNewOrderRequest
     */
    'seel_services'?: Array<OrderCreateNewOrderRequestSeelServicesInner>;
    /**
     * Additional information for the order
     * @type {object}
     * @memberof OrderCreateNewOrderRequest
     */
    'extra_info'?: object;
}

