/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrderRefundLineItemsInner
 */
export interface OrderRefundLineItemsInner {
    /**
     * 
     * @type {string}
     * @memberof OrderRefundLineItemsInner
     */
    'line_item_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderRefundLineItemsInner
     */
    'quantity'?: number;
}

