/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';
import { Item } from './item';

/**
 * 
 * @export
 * @interface OrderUpdateOrderDetailsRequest
 */
export interface OrderUpdateOrderDetailsRequest {
    /**
     * Order updated timestamp in milliseconds
     * @type {string}
     * @memberof OrderUpdateOrderDetailsRequest
     */
    'updated_ts': string;
    /**
     * The list of items included in the order.
     * @type {Array<Item>}
     * @memberof OrderUpdateOrderDetailsRequest
     */
    'line_items'?: Array<Item>;
    /**
     * 
     * @type {Address}
     * @memberof OrderUpdateOrderDetailsRequest
     */
    'shipping_address'?: Address;
    /**
     * 
     * @type {Customer}
     * @memberof OrderUpdateOrderDetailsRequest
     */
    'customer'?: Customer;
    /**
     * Additional information for the order
     * @type {object}
     * @memberof OrderUpdateOrderDetailsRequest
     */
    'extra_info'?: object;
}

