/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrderCreateNewOrderRequestSeelServicesInner
 */
export interface OrderCreateNewOrderRequestSeelServicesInner {
    /**
     * Cover type of the service
     * @type {string}
     * @memberof OrderCreateNewOrderRequestSeelServicesInner
     */
    'type'?: string;
    /**
     * Price of the service
     * @type {number}
     * @memberof OrderCreateNewOrderRequestSeelServicesInner
     */
    'price'?: number;
    /**
     * Quote ID of the service
     * @type {string}
     * @memberof OrderCreateNewOrderRequestSeelServicesInner
     */
    'quote_id'?: string;
    /**
     * Additional information for the service
     * @type {object}
     * @memberof OrderCreateNewOrderRequestSeelServicesInner
     */
    'extra_info'?: object;
}

