/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductUpdateProductDetailsRequestDimensions } from './product-update-product-details-request-dimensions';
import { ProductUpdateProductDetailsRequestIdentifiers } from './product-update-product-details-request-identifiers';
import { ProductUpdateProductDetailsRequestManufacturerWarranty } from './product-update-product-details-request-manufacturer-warranty';
import { ProductUpdateProductDetailsRequestProductAttributes } from './product-update-product-details-request-product-attributes';
import { ProductUpdateProductDetailsRequestWeight } from './product-update-product-details-request-weight';

/**
 * 
 * @export
 * @interface ProductUpdateProductDetailsRequest
 */
export interface ProductUpdateProductDetailsRequest {
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'merchant_id'?: string;
    /**
     * Variant id, the unique identifier of a product SKU. Use \'product_id\' if the product doesn\'t have any variants.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'variant_id'?: string;
    /**
     * Product id.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'product_id': string;
    /**
     * Name of the product.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'product_title': string;
    /**
     * Title of the variant.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'variant_title'?: string;
    /**
     * The Product Brand or Vendor.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'brand_name': string;
    /**
     * Manufacturer of the item.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'manufacturer'?: string;
    /**
     * Main product category.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'category_1'?: string;
    /**
     * Secondary product category.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'category_2'?: string;
    /**
     * Tertiary product category.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'category_3'?: string;
    /**
     * Fourth level product category.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'category_4'?: string;
    /**
     * Text description of the product.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'product_description'?: string;
    /**
     * URL of the product image.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'image_url'?: string;
    /**
     * List price of the product.
     * @type {number}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'price': number;
    /**
     * Currency of the price (e.g. USD, EUR).
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'currency': string;
    /**
     * Whether the product requires shipping.
     * @type {boolean}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'requires_shipping'?: boolean;
    /**
     * Manufacturer model number.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'model_number'?: string;
    /**
     * Condition - new, used, refurbished.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'condition'?: string;
    /**
     * Stock keeping unit.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'sku'?: string;
    /**
     * 
     * @type {ProductUpdateProductDetailsRequestIdentifiers}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'identifiers'?: ProductUpdateProductDetailsRequestIdentifiers;
    /**
     * 
     * @type {ProductUpdateProductDetailsRequestManufacturerWarranty}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'manufacturer_warranty'?: ProductUpdateProductDetailsRequestManufacturerWarranty;
    /**
     * 
     * @type {ProductUpdateProductDetailsRequestDimensions}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'dimensions'?: ProductUpdateProductDetailsRequestDimensions;
    /**
     * 
     * @type {ProductUpdateProductDetailsRequestWeight}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'weight'?: ProductUpdateProductDetailsRequestWeight;
    /**
     * 
     * @type {ProductUpdateProductDetailsRequestProductAttributes}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'product_attributes'?: ProductUpdateProductDetailsRequestProductAttributes;
    /**
     * Timestamp when the product was created.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'created_ts'?: string;
    /**
     * Timestamp when the product was updated.
     * @type {string}
     * @memberof ProductUpdateProductDetailsRequest
     */
    'updated_ts'?: string;
}

