/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about enabled services for this product.
 * @export
 * @interface ProductEnabledServicesInner
 */
export interface ProductEnabledServicesInner {
    /**
     * Service type (e.g., extended-warranty, buyback-guarantee).
     * @type {string}
     * @memberof ProductEnabledServicesInner
     */
    'service_type'?: string;
    /**
     * Enable/disable selling of the service type on this product.
     * @type {boolean}
     * @memberof ProductEnabledServicesInner
     */
    'is_enabled'?: boolean;
    /**
     * Timestamp when the service was created.
     * @type {string}
     * @memberof ProductEnabledServicesInner
     */
    'created_ts'?: string;
    /**
     * Timestamp when the service was last updated.
     * @type {string}
     * @memberof ProductEnabledServicesInner
     */
    'updated_ts'?: string;
}

