/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductPlan
 */
export interface ProductPlan {
    /**
     * Description of the protection plan.
     * @type {string}
     * @memberof ProductPlan
     */
    'description'?: string;
    /**
     * ID of the protection plan.
     * @type {string}
     * @memberof ProductPlan
     */
    'id': string;
    /**
     * Name of the protection plan.
     * @type {string}
     * @memberof ProductPlan
     */
    'name': string;
    /**
     * Price of the plan.
     * @type {number}
     * @memberof ProductPlan
     */
    'price': number;
    /**
     * The three-letter currency code (ISO 4217 format).
     * @type {string}
     * @memberof ProductPlan
     */
    'currency': string;
    /**
     * The imageUrl for the warranty plan. Use this as the product image for the warranty plan SKU(s) in your store.
     * @type {string}
     * @memberof ProductPlan
     */
    'image_url'?: string;
    /**
     * A link to the extended warranty plan terms and information. Any offer display must include a “Learn More” or “See Plan Details” call-to-action that enables the customer to see exactly what the warranty plan covers.
     * @type {string}
     * @memberof ProductPlan
     */
    'url'?: string;
    /**
     * The length of term in months.
     * @type {number}
     * @memberof ProductPlan
     */
    'term_length': number;
    /**
     * \"immediate\" - right after purchase \"after\" - coverage starts after the manufacturer\'s warranty has expired
     * @type {string}
     * @memberof ProductPlan
     */
    'coverage_starts': string;
    /**
     * \"base”, which means the extended warranty is a base plan covering mechanical and electrical failures through normal use, or “adh”, which means the plan includes coverage for accidental damage (i.e. “Accidental Damage in Handling”)
     * @type {string}
     * @memberof ProductPlan
     */
    'coverage_includes': string;
    /**
     * “replacement” (the damaged item is replaced by a new or refurbished equivalent), “repair_depot” (the customer mails the damaged item to a repair facility), or “repair_onsite” (a repair technician goes out to the customer’s home to repair the item)
     * @type {string}
     * @memberof ProductPlan
     */
    'service_type': string;
    /**
     * Indicates whether the damaged item will be replaced by a “new” or “refurbished” item.
     * @type {string}
     * @memberof ProductPlan
     */
    'replacement_type': string;
    /**
     * The amount of the deductible charged to the customer during a claim, if there is one. For most Extend protection plans, there is no deductible.
     * @type {number}
     * @memberof ProductPlan
     */
    'deductible': number;
}

