/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the manufacturer\'s warranty. This is optional, but if you can provide it please do as it can significantly speed up the warranty matching process.
 * @export
 * @interface ProductManufacturerWarranty
 */
export interface ProductManufacturerWarranty {
    /**
     * A URL linking to the full details of the manufacturer\'s warranty, probably on the manufacturer\'s website.
     * @type {string}
     * @memberof ProductManufacturerWarranty
     */
    'url'?: string;
    /**
     * The length of the manufacturer warranty coverage in months.
     * @type {number}
     * @memberof ProductManufacturerWarranty
     */
    'term_length'?: number;
}

