/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Other product attributes.
 * @export
 * @interface ProductAddNewProductRequestProductAttributes
 */
export interface ProductAddNewProductRequestProductAttributes {
    /**
     * Color of the product.
     * @type {string}
     * @memberof ProductAddNewProductRequestProductAttributes
     */
    'color'?: string;
    /**
     * Size of the product.
     * @type {string}
     * @memberof ProductAddNewProductRequestProductAttributes
     */
    'size'?: string;
}

