/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Product weight.
 * @export
 * @interface ProductWeight
 */
export interface ProductWeight {
    /**
     * Weight of the product.
     * @type {number}
     * @memberof ProductWeight
     */
    'value'?: number;
    /**
     * Unit of weight (e.g., g, oz, lb, kg).
     * @type {string}
     * @memberof ProductWeight
     */
    'unit'?: string;
}

