/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductIdentifiers
 */
export interface ProductIdentifiers {
    /**
     * Serial number of a specific product unit.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'serial_number'?: string;
    /**
     * Global Trade Item Number identifier.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'gtin'?: string;
    /**
     * Universal Product Code identifier.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'upc'?: string;
    /**
     * International Standard Book Number identifier.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'isbn'?: string;
    /**
     * Barcode identifying the product.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'barcode'?: string;
}

