/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductAttributes
 */
export interface ProductAttributes {
    /**
     * The color of the product.
     * @type {string}
     * @memberof ProductAttributes
     */
    'color'?: string;
    /**
     * The size of the product.
     * @type {string}
     * @memberof ProductAttributes
     */
    'size'?: string;
}

