/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductDimensions } from './product-dimensions';
import { ProductEnabledServicesInner } from './product-enabled-services-inner';
import { ProductIdentifiers } from './product-identifiers';
import { ProductManufacturerWarranty } from './product-manufacturer-warranty';
import { ProductProductAttributes } from './product-product-attributes';
import { ProductWeight } from './product-weight';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof Product
     */
    'merchant_id'?: string;
    /**
     * Variant id, the unique identifier of a product SKU. Use \'product_id\' if the product doesn\'t have any variants.
     * @type {string}
     * @memberof Product
     */
    'variant_id'?: string;
    /**
     * Product id.
     * @type {string}
     * @memberof Product
     */
    'product_id': string;
    /**
     * Name of the product.
     * @type {string}
     * @memberof Product
     */
    'product_title': string;
    /**
     * Title of the variant.
     * @type {string}
     * @memberof Product
     */
    'variant_title'?: string;
    /**
     * The Product Brand or Vendor.
     * @type {string}
     * @memberof Product
     */
    'brand_name': string;
    /**
     * Manufacturer of the item.
     * @type {string}
     * @memberof Product
     */
    'manufacturer'?: string;
    /**
     * Main product category.
     * @type {string}
     * @memberof Product
     */
    'category_1'?: string;
    /**
     * Secondary product category.
     * @type {string}
     * @memberof Product
     */
    'category_2'?: string;
    /**
     * Tertiary product category.
     * @type {string}
     * @memberof Product
     */
    'category_3'?: string;
    /**
     * Fourth level product category.
     * @type {string}
     * @memberof Product
     */
    'category_4'?: string;
    /**
     * Text description of the product.
     * @type {string}
     * @memberof Product
     */
    'product_description'?: string;
    /**
     * URL of the product image.
     * @type {string}
     * @memberof Product
     */
    'image_url'?: string;
    /**
     * List price of the product.
     * @type {number}
     * @memberof Product
     */
    'price': number;
    /**
     * Currency of the price (e.g. USD, EUR).
     * @type {string}
     * @memberof Product
     */
    'currency': string;
    /**
     * Whether the product requires shipping.
     * @type {boolean}
     * @memberof Product
     */
    'requires_shipping'?: boolean;
    /**
     * Manufacturer model number.
     * @type {string}
     * @memberof Product
     */
    'model_number'?: string;
    /**
     * Condition - new, used, refurbished.
     * @type {string}
     * @memberof Product
     */
    'condition'?: string;
    /**
     * Stock keeping unit.
     * @type {string}
     * @memberof Product
     */
    'sku'?: string;
    /**
     * 
     * @type {ProductIdentifiers}
     * @memberof Product
     */
    'identifiers'?: ProductIdentifiers;
    /**
     * 
     * @type {ProductManufacturerWarranty}
     * @memberof Product
     */
    'manufacturer_warranty'?: ProductManufacturerWarranty;
    /**
     * 
     * @type {ProductDimensions}
     * @memberof Product
     */
    'dimensions'?: ProductDimensions;
    /**
     * 
     * @type {ProductWeight}
     * @memberof Product
     */
    'weight'?: ProductWeight;
    /**
     * 
     * @type {ProductProductAttributes}
     * @memberof Product
     */
    'product_attributes'?: ProductProductAttributes;
    /**
     * Timestamp when the product was created.
     * @type {string}
     * @memberof Product
     */
    'created_ts'?: string;
    /**
     * Timestamp when the product was updated.
     * @type {string}
     * @memberof Product
     */
    'updated_ts'?: string;
    /**
     * 
     * @type {Array<ProductEnabledServicesInner>}
     * @memberof Product
     */
    'enabled_services'?: Array<ProductEnabledServicesInner>;
}

