/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Product } from './product';

/**
 * List of products.
 * @export
 * @interface ProductBatchCreateProductsRequest
 */
export interface ProductBatchCreateProductsRequest {
    /**
     * The list of products.
     * @type {Array<Product>}
     * @memberof ProductBatchCreateProductsRequest
     */
    'products'?: Array<Product>;
}

