/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductAddNewProductRequestDimensions } from './product-add-new-product-request-dimensions';
import { ProductAddNewProductRequestIdentifiers } from './product-add-new-product-request-identifiers';
import { ProductAddNewProductRequestManufacturerWarranty } from './product-add-new-product-request-manufacturer-warranty';
import { ProductAddNewProductRequestProductAttributes } from './product-add-new-product-request-product-attributes';
import { ProductAddNewProductRequestWeight } from './product-add-new-product-request-weight';

/**
 * 
 * @export
 * @interface ProductAddNewProductRequest
 */
export interface ProductAddNewProductRequest {
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'merchant_id'?: string;
    /**
     * Variant id, the unique identifier of a product SKU. Use \'product_id\' if the product doesn\'t have any variants.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'variant_id'?: string;
    /**
     * Product id.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'product_id': string;
    /**
     * Name of the product.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'product_title': string;
    /**
     * Title of the variant.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'variant_title'?: string;
    /**
     * The Product Brand or Vendor.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'brand_name': string;
    /**
     * Manufacturer of the item.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'manufacturer'?: string;
    /**
     * Main product category.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'category_1'?: string;
    /**
     * Secondary product category.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'category_2'?: string;
    /**
     * Tertiary product category.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'category_3'?: string;
    /**
     * Fourth level product category.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'category_4'?: string;
    /**
     * Text description of the product.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'product_description'?: string;
    /**
     * URL of the product image.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'image_url'?: string;
    /**
     * List price of the product.
     * @type {number}
     * @memberof ProductAddNewProductRequest
     */
    'price': number;
    /**
     * Currency of the price (e.g. USD, EUR).
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'currency': string;
    /**
     * Whether the product requires shipping.
     * @type {boolean}
     * @memberof ProductAddNewProductRequest
     */
    'requires_shipping'?: boolean;
    /**
     * Manufacturer model number.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'model_number'?: string;
    /**
     * Condition - new, used, refurbished.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'condition'?: string;
    /**
     * Stock keeping unit.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'sku'?: string;
    /**
     * 
     * @type {ProductAddNewProductRequestIdentifiers}
     * @memberof ProductAddNewProductRequest
     */
    'identifiers'?: ProductAddNewProductRequestIdentifiers;
    /**
     * 
     * @type {ProductAddNewProductRequestManufacturerWarranty}
     * @memberof ProductAddNewProductRequest
     */
    'manufacturer_warranty'?: ProductAddNewProductRequestManufacturerWarranty;
    /**
     * 
     * @type {ProductAddNewProductRequestDimensions}
     * @memberof ProductAddNewProductRequest
     */
    'dimensions'?: ProductAddNewProductRequestDimensions;
    /**
     * 
     * @type {ProductAddNewProductRequestWeight}
     * @memberof ProductAddNewProductRequest
     */
    'weight'?: ProductAddNewProductRequestWeight;
    /**
     * 
     * @type {ProductAddNewProductRequestProductAttributes}
     * @memberof ProductAddNewProductRequest
     */
    'product_attributes'?: ProductAddNewProductRequestProductAttributes;
    /**
     * Timestamp when the product was created.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'created_ts'?: string;
    /**
     * Timestamp when the product was updated.
     * @type {string}
     * @memberof ProductAddNewProductRequest
     */
    'updated_ts'?: string;
}

