/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';
import { Item } from './item';

/**
 * 
 * @export
 * @interface QuoteGenerateQuoteRequest
 */
export interface QuoteGenerateQuoteRequest {
    /**
     * The ID of a cart.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'cart_id'?: string;
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'merchant_id'?: string;
    /**
     * The ID of the shopping session.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'session_id': string;
    /**
     * The ID of the client device.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'device_id'?: string;
    /**
     * The IP address of the client.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'client_ip'?: string;
    /**
     * The type of the quote.
     * @type {string}
     * @memberof QuoteGenerateQuoteRequest
     */
    'type': string;
    /**
     * The list of items included in the quote.
     * @type {Array<Item>}
     * @memberof QuoteGenerateQuoteRequest
     */
    'line_items': Array<Item>;
    /**
     * 
     * @type {Address}
     * @memberof QuoteGenerateQuoteRequest
     */
    'shipping_address': Address;
    /**
     * 
     * @type {Customer}
     * @memberof QuoteGenerateQuoteRequest
     */
    'customer': Customer;
    /**
     * Additional information for the quote
     * @type {object}
     * @memberof QuoteGenerateQuoteRequest
     */
    'extra_info'?: object;
}

