/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';
import { Item } from './item';

/**
 * 
 * @export
 * @interface Quote
 */
export interface Quote {
    /**
     * The ID of the quote.
     * @type {string}
     * @memberof Quote
     */
    'quote_id'?: string;
    /**
     * The ID of a cart.
     * @type {string}
     * @memberof Quote
     */
    'cart_id'?: string;
    /**
     * The unique identifier for the merchant within Seel\'s system.
     * @type {string}
     * @memberof Quote
     */
    'merchant_id'?: string;
    /**
     * The ID of the session.
     * @type {string}
     * @memberof Quote
     */
    'session_id'?: string;
    /**
     * The ID of the client device.
     * @type {string}
     * @memberof Quote
     */
    'device_id'?: string;
    /**
     * The IP address of the client.
     * @type {string}
     * @memberof Quote
     */
    'client_ip'?: string;
    /**
     * The type of the quote.
     * @type {string}
     * @memberof Quote
     */
    'type'?: string;
    /**
     * The price of the quote.
     * @type {number}
     * @memberof Quote
     */
    'price'?: number;
    /**
     * The three-letter currency code (ISO 4217 format), i.e. USD etc.
     * @type {string}
     * @memberof Quote
     */
    'currency'?: string;
    /**
     * The status of the quote.
     * @type {string}
     * @memberof Quote
     */
    'status'?: QuoteStatusEnum;
    /**
     * Quote created timestamp in milliseconds
     * @type {string}
     * @memberof Quote
     */
    'created_ts'?: string;
    /**
     * The list of items included in the quote.
     * @type {Array<Item>}
     * @memberof Quote
     */
    'line_items'?: Array<Item>;
    /**
     * 
     * @type {Address}
     * @memberof Quote
     */
    'shipping_address'?: Address;
    /**
     * 
     * @type {Customer}
     * @memberof Quote
     */
    'customer'?: Customer;
    /**
     * Additional information for the order
     * @type {object}
     * @memberof Quote
     */
    'extra_info'?: object;
}

type QuoteStatusEnum = 'accepted' | 'rejected'


