/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SeelServiceCoveredItemsInner
 */
export interface SeelServiceCoveredItemsInner {
    /**
     * The id of the item
     * @type {string}
     * @memberof SeelServiceCoveredItemsInner
     */
    'line_item_id'?: string;
    /**
     * The quantity of the item.
     * @type {number}
     * @memberof SeelServiceCoveredItemsInner
     */
    'quantity'?: number;
}

