/*
Seel API

Seel API

The version of the OpenAPI document: 1.3.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ShippingDetails
 */
export interface ShippingDetails {
    /**
     * The weight of the line item in grams. Used to calculate shipping costs.
     * @type {number}
     * @memberof ShippingDetails
     */
    'weight_g'?: number;
    /**
     * The length of the line item package in centimeters.
     * @type {number}
     * @memberof ShippingDetails
     */
    'length_cm'?: number;
    /**
     * The height of the line item package in centimeters.
     * @type {number}
     * @memberof ShippingDetails
     */
    'height_cm'?: number;
    /**
     * The width of the line item package in centimeters.
     * @type {number}
     * @memberof ShippingDetails
     */
    'width_cm'?: number;
    /**
     * The calculated shipping cost for delivering this particular line item
     * @type {number}
     * @memberof ShippingDetails
     */
    'shipping_cost'?: number;
}

